<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.vlts</groupId>
        <artifactId>octopus-build</artifactId>
        <version>${revision}</version>
        <relativePath>./octopus-build/pom.xml</relativePath>
    </parent>
    <artifactId>octopus</artifactId>
    <packaging>pom</packaging>
    <name>octopus ${project.version}</name>
    <description>parent for Octopus built with Maven</description>
    <modules>
        <module>octopus-build</module>
        <module>octopus-dependencies</module>
        <module>octopus-admin</module>
        <module>octopus-gateway</module>
        <module>octopus-core</module>
    </modules>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>cn.vlts</groupId>
                <artifactId>octopus-dependencies</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
