<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.vlts</groupId>
        <artifactId>octopus</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>octopus-gateway</artifactId>
    <packaging>jar</packaging>
    <name>octopus-gateway ${project.version}</name>
    <description>gateway module for Octopus built with Maven</description>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
    </dependencies>
</project>