<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.vlts</groupId>
        <artifactId>octopus-build</artifactId>
        <version>${revision}</version>
        <relativePath>../octopus-build/pom.xml</relativePath>
    </parent>
    <artifactId>octopus-dependencies</artifactId>
    <name>octopus-dependencies ${project.version}</name>
    <description>dependencies for Octopus built with Maven</description>
    <packaging>pom</packaging>
    <properties>
        <lombok.version>1.18.34</lombok.version>
        <spring-boot.version>3.3.3</spring-boot.version>
        <vertx.version>4.5.10</vertx.version>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>io.vertx</groupId>
                <artifactId>vertx-stack-depchain</artifactId>
                <version>${vertx.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>